### ISSUE TITLE
Disable buttons when processing

### ISSUE THREAD

**Issue by fayaz07** [stackinflow/focial#25]
## Issue
While logging in, once the button is clicked, then the should be disabled.

## Ways to solve
[OTS] provides a property `isModal`, we can set it true to disable interactivity for the screen when the loader is shown

**Comment by diegoalvis** [comment]
I'd like to work on this. Feel free to assign it to me 🙂

**Comment by fayaz07** [comment]
Hi @diegoalvis , please feel free to join our [gitter](https://gitter.im/stackinflow/focial) channel and let us know what you are going to do, so that other fellowmates also know.

**Comment by diegoalvis** [comment]
Btw perhaps you want to add **hacktoberfest** topic to the repo if you wish to participate in [Hacktoberfest](https://hacktoberfest.digitalocean.com/)

**Comment by prudhvir3ddy** [comment]
@diegoalvis thanks for the reminder, added it.
