### ISSUE TITLE
Fix linter issues

### ISSUE THREAD

**Issue by fayaz07** [stackinflow/focial#54]
Run `flutter analyze`, checkout the issues thrown out by the linter try to solve them :)

**Comment by asadmansr** [comment]
Hi @fayaz07, I ran the `flutter analyze` command and there are over 450 issues. I can start tackling the error ones first (not sure how much I can complete)

![Screen Shot 2020-10-04 at 10 07 24 PM](https://user-images.githubusercontent.com/7865693/95034041-3dfc4e00-068e-11eb-81e1-3646f724a296.png)

**Comment by fayaz07** [comment]
Hi @asadmansr they are lint errors, you don't have to know rocket science to do that, your IDE will help you out. Please join our slack channel for more discussions.

Thanks

**Comment by harshshinde07** [comment]
Hi @fayaz07 , While solving this issue, the linter is suggesting `info: Prefer using lowerCamelCase for constant names.` for all the constants . So do I need to change the casing or should I suppress the warning?

Thanks

**Comment by fayaz07** [comment]
@prudhvir3ddy what do you say?

**Comment by harshshinde07** [comment]
Can someone let me know how should I move forward? I'd suggest to keep them as they are

**Comment by fayaz07** [comment]
Yeah you can go ahead with what is required by the linter
